consumes:
- application/json
definitions:
  service_info:
    type: object
    required:
      - description
      - service
      - version
    properties:
      description:
        type: string
        minLength: 1
      service:
        type: string
        minLength: 1
      version:
        type: string
        minLength: 1
  resource_type_out:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        minLength: 36
        maxLength: 36
      name:
        type: string
        minLength: 1
      description:
        type: string
  resource_types_out:
    type: object
    required:
      - resource_types
    properties:
      resource_types:
        type: array
        items:
          $ref: "#/definitions/resource_type_out"
info:
  description: Manages Permissions for the CyVerse Discovery Environment and related
    applications
  title: Permissions Service
  version: 5.2.6.0
paths:
  /:
    get:
      tags:
        - status
      responses:
        200:
          description: service status information
          schema:
            $ref: "#/definitions/service_info"
  /resource_types:
    get:
      tags:
        - resource_types
      responses:
        200:
          description: resource type listing
          schema:
            $ref: "#/definitions/resource_types_out"
produces:
- application/json
schemes:
- http
swagger: "2.0"
