consumes:
  - application/json
definitions:
  error_out:
    type: object
    description: "The standard format for an error response body."
    required:
      - reason
    properties:
      reason:
        type: string
        description: "The reason for the error."
        minLength: 1
  service_info:
    type: object
    required:
      - description
      - service
      - version
    properties:
      description:
        type: string
        description: "A brief description of the service."
        minLength: 1
      service:
        type: string
        description: "The name of the service."
        minLength: 1
      version:
        type: string
        description: "The service's version number."
        minLength: 1
  resource_type_in:
    type: object
    description: "An incoming resource type."
    required:
      - name
    properties:
      name:
        type: string
        description: "The name of the resource type."
        minLength: 1
      description:
        type: string
        description: "A brief description of the resource type."
  resource_type_out:
    type: object
    description: "An outgoing resource type."
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: "The resource type identifier."
        minLength: 36
        maxLength: 36
      name:
        type: string
        description: "The name of the resource type."
        minLength: 1
      description:
        type: string
        description: "A brief description of the resource type."
  resource_types_out:
    type: object
    description: "A list of resource types."
    required:
      - resource_types
    properties:
      resource_types:
        type: array
        description: "The list of resource types."
        items:
          $ref: "#/definitions/resource_type_out"
info:
  description: >-
    Manages Permissions for the CyVerse Discovery Environment and related applications.
  title: "Permissions Service"
  version: "5.2.6.0"
paths:
  /:
    get:
      tags:
        - status
      summary: "Service Status Information"
      description: >-
        Displays general information about the service and can be used to determine whether or not the service is
        running.
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/service_info"
  /resource_types:
    get:
      tags:
        - resource_types
      summary: "List Resource Types"
      description: >-
        Lists resource types known to the permissions service. A resource type represents a class of resources to
        which permissions may be applied. For example, the Discovery environment has apps collectively defined as
        a single resource type in the permissions service.
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/resource_types_out"
        500:
          $ref: "#/responses/internal_server_error"
    put:
      tags:
        - resource_types
      summary: "Add a Resource Type"
      description: >-
        Adds a resource type to the list of available resource types. The name of the resource type must be unique.
      parameters:
        - description: "The resource type to add."
          in: body
          name: "resource_type_in"
          required: True
          schema:
            $ref: "#/definitions/resource_type_in"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/resource_type_out"
        400:
          $ref: "#/responses/bad_request"
        500:
          $ref: "#/responses/internal_server_error"
  /resource_types/{id}:
    parameters:
      - name: id
        type: string
        description: "The resource type ID."
        in: path
        required: True
    post:
      tags:
        - resource_types
      summary: "Update a Resource Type"
      description: >-
        Updates the name or description of a resource type. The new name of the resource type must be unique if one
        is provided.
      parameters:
        - description: "The new name and description of the resource type."
          in: body
          name: "resource_type_in"
          required: True
          schema:
            $ref: "#/definitions/resource_type_in"
      responses:
        200:
          description: "Updated"
          schema:
            $ref: "#/definitions/resource_type_out"
        400:
          $ref: "#/responses/bad_request"
        404:
          $ref: "#/responses/not_found"
        500:
          $ref: "#/responses/internal_server_error"
    delete:
      tags:
        - resource_types
      summary: "Delete a Resource Type"
      description: >-
        Removes a resource type from the database. A resource type may only be removed if there are no resources
        associated with it.
      responses:
        200:
          description: "Deleted"
        400:
          $ref: "#/responses/bad_request"
        404:
          $ref: "#/responses/not_found"
        500:
          $ref: "#/responses/internal_server_error"
produces:
  - application/json
responses:
  bad_request:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/error_out"
  internal_server_error:
    schema:
      $ref: "#/definitions/error_out"
  not_found:
    description: "Not Found"
    schema:
      $ref: "#/definitions/error_out"
schemes:
  - http
swagger: "2.0"
